name: ais
description: Decode AIS messages
version: 0.0.9
homepage: https://github.com/jamesdalby/ais

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nmea:
    git:
      url: https://github.com/jamesdalby/nmea.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
